spring:
  application:
    name: product-app-producer
  rabbitmq:
    host: ${host:localhost}
    username: ${user:guest}
    password: ${pass:guest}
    port: ${port:5672}
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 2000ms
          multiplier: 2
    cache:
      connection:
        mode: channel
