spring:
  application:
    name: product-app-consumer
  rabbitmq:
    host: ${host:localhost}
    username: ${user:mateusgobo}
    password: ${pass:mateusgobo}
    port: ${port:5672}
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 2000ms
          multiplier: 2
        consumers-per-queue: ${consumers:100}
    cache:
      connection:
        mode: channel
  datasource:
    url: jdbc:postgresql://localhost:5433/product-db
    username: sa
    password: 456
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      dialect: postgresql

  mail:
    host: smtp.mailtrap.io
    port: 587
    username: edd41a70512377
    password: 27b5d018c48be2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
